### ISSUE TITLE
Missing "remove spaces" option

### ISSUE THREAD

**Issue by iSimonWeb** [patrickkettner/grunt-compile-handlebars#45]
Hi there dude! What about adding an option to uglify the compiled HTMLs?
It could be really useful when playing with inline-block positioned elements.
Thanks a lot! Nice task :+1:

**Comment by patrickkettner** [comment]
Hiya!

Thanks a lot! I am not quite sure what you are envisioning though.
Handlebars doesn't have an option for this, so it seems like it would make
sense to use another grunt task for this job, or the `{{~` syntax inside of
your template to squish it to the left.

Lemme know if I am misunderstanding something

Cheers!
Patrick

**Comment by patrickkettner** [comment]
closing from a lack of updates, please do let me know if I misunderstood what you meant, @iSimonWeb!
