### ISSUE TITLE
Support Handlebars 3.x

### ISSUE THREAD

**Issue by lostthetrail** [patrickkettner/grunt-compile-handlebars#51]
Handlebars 3.x is the latest version of Handlebars and has major interface differences between 2.x.

**Comment by patrickkettner** [comment]
whats broken?

**Comment by patrickkettner** [comment]
All tests pass on 3.0, and the semver specified is suuuuuuuper loose (`>= 1`) so has technically been the default since the immediate release of 3.0

Please open up an issue if there anything has broken

thanks!
