### ISSUE TITLE
Includes

### ISSUE THREAD

**Issue by iamdriz** [patrickkettner/grunt-compile-handlebars#53]
How do I use includes (partials) with this module?

So basically I want to export a file called `index.html` from `index.handlebars` which will have a header and footer that are stored in `_header.handlebars` and `_footer.handlebars`.

I have this in my `Gruntfile.js`

~~~
grunt.initConfig({
	pkg: grunt.file.readJSON('package.json'),
	compile-handlebars: {
		files: [{
			src: 'src/index.handlebars',
			dest: 'dist/index.html'
		}]
	}
});
~~~

What should be inside the `index.handlebars` to include them? As usually you have to use the Handlebars compile function to create partials... does this support something like what you can do in Jade and just do an `include(_header)` ?

**Comment by patrickkettner** [comment]
You add partials to your config object then reference them like you normally would.

```javascript
grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    compile-handlebars: {
        files: [{
            src: 'src/index.handlebars',
            dest: 'dist/index.html'
        }],
        partials: ['partials/_*.handlebars']
    }
});
```

```handlebars
{{> _header}}
CONTENT!
{{> _footer}}
```
