### ISSUE TITLE
Arguments to path.join must be strings

### ISSUE THREAD

**Issue by iamdriz** [patrickkettner/grunt-compile-handlebars#54]
I get the following error `Arguments to path.join must be strings` when trying to run this task:

~~~
grunt.initConfig({
	pkg: grunt.file.readJSON('package.json'),
	'compile-handlebars': {
		allStatic: {
			files: [{
				src: 'src/index.handlebars',
				dest: 'dist/index.html'
			}],
			partials: ['src/partials/_*.handlebars']
		}
	}
});
~~~

Any ideas what the issue is?

**Comment by patrickkettner** [comment]
What's the full stack with line numbers

**Comment by iamdriz** [comment]
How do I get that? I only get that error when I run grunt in the cmd...

**Comment by patrickkettner** [comment]
Sorry - I just meant what is the full error? What is entirety of the
terminal output

**Comment by iamdriz** [comment]
Exactly that. Except for the message to use force. But there is no more displayed.

**Comment by patrickkettner** [comment]
please copy and paste the entriety of the message.

On Mon, Jun 8, 2015 at 4:18 PM, iamdriz <notifications@github.com> wrote:

> Exactly that. Except for the message to use force. But there is no more
> displayed.
>
> Sent from my iPhone
>
> > On 8 Jun 2015, at 18:58, patrick kettner <notifications@github.com>
> wrote:
> >
> > Sorry - I just meant what is the full error? What is entirety of the
> > terminal output
> >
> > On Mon, Jun 8, 2015, 1:46 PM iamdriz <notifications@github.com> wrote:
> >
> > > How do I get that? I only get that error when I run grunt in the cmd...
> > >
> > > Sent from my iPhone
> > >
> > > > On 8 Jun 2015, at 17:40, patrick kettner <notifications@github.com>
> > > wrote:
> > > >
> > > > What's the full stack with line numbers
> > > >
> > > > On Mon, Jun 8, 2015, 12:39 PM iamdriz <notifications@github.com>
> wrote:
> > > >
> > > > > I get the following error Arguments to path.join must be strings
> when
> > > > > trying to run this task:
> > > > >
> > > > > grunt.initConfig({
> > > > > pkg: grunt.file.readJSON('package.json'),
> > > > > 'compile-handlebars': {
> > > > > allStatic: {
> > > > > files: [{
> > > > > src: 'src/index.handlebars',
> > > > > dest: 'dist/index.html'
> > > > > }],
> > > > > partials: ['src/partials/_*.handlebars']
> > > > > }
> > > > > }
> > > > > });
> > > > >
> > > > > Any ideas what the issue is?
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> https://github.com/patrickkettner/grunt-compile-handlebars/issues/54
> > > >.
> > > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/patrickkettner/grunt-compile-handlebars/issues/54#issuecomment-110089999
> >
>
> > > .
> > >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/patrickkettner/grunt-compile-handlebars/issues/54#issuecomment-110125208>
> .
>



-- 
patrick

**Comment by iamdriz** [comment]
C:\_Projects\Handlebars>grunt
Running "compile-handlebars:allStatic" (compile-handlebars) task
Warning Arguments to path.join must be strings Use --force to continue.

**Comment by patrickkettner** [comment]
could you run `grunt --stack` and then paste the results

**Comment by iamdriz** [comment]
~~~
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\System32>cd C:\_Projects\Handlebars

C:\_Projects\Handlebars>grunt --stack
Running "compile-handlebars:allStatic" (compile-handlebars) task
Warning: Arguments to path.join must be strings Use --force to continue.
TypeError: Arguments to path.join must be strings
    at f (path.js:204:15)
    at Object.filter (native)
    at Object.exports.join (path.js:209:40)
    at Object.file.exists (C:\_Projects\Handlebars\node_modules\gr
unt\lib\grunt\file.js:381:28)
    at getTemplateData (C:\_Projects\Handlebars\node_modules\grunt
-compile-handlebars\tasks\compile-handlebars.js:141:20)
    at compile (C:\_Projects\Handlebars\node_modules\grunt-compile
-handlebars\tasks\compile-handlebars.js:227:26)
    at C:\_Projects\Handlebars\node_modules\grunt-compile-handleba
rs\tasks\compile-handlebars.js:274:13
    at Array.forEach (native)
    at C:\_Projects\Handlebars\node_modules\grunt-compile-handleba
rs\tasks\compile-handlebars.js:273:20
    at Array.forEach (native)

Aborted due to warnings.

C:\_Projects\Handlebars>
~~~

**Comment by patrickkettner** [comment]
following the line in the stack trace, its failing because there isn't a `templateData` section in your configuration. You need to add that in order to have a data source for your templates

**Comment by iamdriz** [comment]
Okay setting the templateData to `''` fixes it. Thanks.

**Comment by sumayku-design** [comment]
sorry have same issue, i'm new in grunt what is `templeteData ` do you mean

**Comment by patrickkettner** [comment]
hi @sumayku-design!
`templeteData` is something specific to this grunt plugin. It is one of the options you set in your grunt config
