### ISSUE TITLE
Foreign characters missing

### ISSUE THREAD

**Issue by eivers88** [patrickkettner/grunt-compile-handlebars#57]
For example, in my json file I have:

`{ "myText" : "manillar de compilación gruñido" }`

after creating a build I get this in my html:

`manillar de compilaci�n gru�ido`

Does anyone have any insight on why the special foreign characters aren't getting through? 

Thanks,
-Aaron

**Comment by patrickkettner** [comment]
Hey Aaron!
What are you using to view your output?

**Comment by eivers88** [comment]
I was using WebStorm but also double checked in Notepadd++ and Chrome

**Comment by patrickkettner** [comment]
@eivers88 I am not able to replicate this issue locally. It seems like it may be an encoding issue of the document you are using, however that wouldn't normally show up in an editor. Would you be able to post a config/gist/something so I can debug this further?

**Comment by eivers88** [comment]
@patrickkettner Alright I through together a gist: https://gist.github.com/eivers88/cfa6a1c6e7901f6d39cc
Hopefully that makes sense, let me know if there is something else I can do to help.

**Comment by patrickkettner** [comment]
hey @eivers88!
I am so sorry it took so long to get back to you!

I am still not able to replicate the issue

When I run your project locally I get the following

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Título De La Página</title>
    <link rel="stylesheet" href="../assets/styles/main.css"/>
</head>
<body>
<h1>Título De La Página</h1><h2>Página principal Título</h2>
<p>manillar de compilación gruñido</p>    <script src="../assets/js/main.js"></script>
</body>
</html>
```


Can you elaborate on your setup (OS, browser, etc). A live code sample would be groovy
