### ISSUE TITLE
Add possibility to use different files as templateData? 

### ISSUE THREAD

**Issue by ruben1** [patrickkettner/grunt-compile-handlebars#59]
```js
var data;
if (Array.isArray(templateData)) {
    data = templateData[index];
    if (data) {
        return data;
    }

    grunt.log.error('You need to assign the same number of data files as source files when using array notation.');
}
```
So it looks like we can only use one template data to insert variables into templates. Is it possible to insert different data sources into the same file with a single output ?

**Comment by patrickkettner** [comment]
hey @ruben1!
I am not following the question - could you be more detailed in what you are wanting to do?
